# Generated by Django 5.0.6 on 2024-09-02 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_room_options_room_participants'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-updated_at', '-created_at']},
        ),
    ]
